### ISSUE TITLE
How make the buttons on Left Side Workable?

### ISSUE THREAD

**Issue by rohitornots** [developedbyed/glass-website#10]
Can Someone pls help me regarding this issue?
I want to make those buttons when clicked, redirect to a link specified by me.
Any idea of how to do it?
Thanks

**Comment by CodeRadu** [comment]
Put everything in the `<div class="link">` into an `a` tag and specify the `href="<page_url>"`

**Comment by sanskar240** [comment]
You could create a new div class and type in the url or use the "on click event" function in javascript.

**Comment by rohitornots** [comment]
Thanks
