### ISSUE TITLE
What is this design software used in the video?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [developedbyed/glass-website#11]
![Awesome Glass UI Design Tutorial 00-10-42 ](https://user-images.githubusercontent.com/12076232/107715991-5e5aaa00-6d0b-11eb-8b2b-cf62721e37c1.png)

**Comment by ghost** [comment]
[figma](https://www.figma.com/)

**Comment by Yakumo-Yukari** [comment]
> [figma](https://www.figma.com/)

Thank you very much,have good day
